#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

nohup /etc/alternatives/java_sdk_1.8.0/bin/java -jar $OPENSHIFT_REPO_DIR/match-api/target/*.jar --spring.profiles.active=openshift --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
