#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

alias javac='/etc/alternatives/java_sdk_1.8.0/bin/javac'
alias java='/etc/alternatives/java_sdk_1.8.0/bin/java'
javac -version
java -version

nohup java -jar match-api/target/*.jar -Dspring.profiles.active=openshift --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
